import type { Transformer } from "@lexical/markdown";
import type { AnyLexicalExtensionArgument } from "lexical";

import { BREAK_SYNTAX_EXTENSION } from "./break";
import {
  CODE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  CODE_SYNTAX_EXTENSION,
  CODE_SYNTAX_REACT_EXTENSION,
} from "./code";
import { HEADING_MARKDOWN_SHORTCUT_TRANSFORMERS, HEADING_SYNTAX_EXTENSION } from "./heading";
import { IMAGE_MARKDOWN_SHORTCUT_TRANSFORMERS, IMAGE_SYNTAX_EXTENSION } from "./image";
import {
  INLINE_MARK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  INLINE_MARK_SYNTAX_EXTENSION,
} from "./inline-mark";
import {
  LINK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  LINK_SYNTAX_EXTENSION,
  LINK_SYNTAX_REACT_EXTENSION,
} from "./link";
import { LIST_MARKDOWN_SHORTCUT_TRANSFORMERS, LIST_SYNTAX_EXTENSION } from "./list";
import { PARAGRAPH_SYNTAX_EXTENSION } from "./paragraph";
import { QUOTE_MARKDOWN_SHORTCUT_TRANSFORMERS, QUOTE_SYNTAX_EXTENSION } from "./quote";
import {
  TABLE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  TABLE_SYNTAX_EXTENSION,
  TABLE_SYNTAX_REACT_EXTENSION,
} from "./table";
import { TEXT_SYNTAX_EXTENSION } from "./text";
import {
  THEMATIC_BREAK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  THEMATIC_BREAK_SYNTAX_EXTENSION,
} from "./thematic-break";

export const SYNTAX_EXTENSIONS: ReadonlyArray<AnyLexicalExtensionArgument> = [
  BREAK_SYNTAX_EXTENSION,
  HEADING_SYNTAX_EXTENSION,
  QUOTE_SYNTAX_EXTENSION,
  LIST_SYNTAX_EXTENSION,
  TABLE_SYNTAX_EXTENSION,
  THEMATIC_BREAK_SYNTAX_EXTENSION,
  CODE_SYNTAX_EXTENSION,
  TEXT_SYNTAX_EXTENSION,
  INLINE_MARK_SYNTAX_EXTENSION,
  IMAGE_SYNTAX_EXTENSION,
  LINK_SYNTAX_EXTENSION,
  PARAGRAPH_SYNTAX_EXTENSION,
];

export const SYNTAX_REACT_EXTENSIONS: ReadonlyArray<AnyLexicalExtensionArgument> = [
  LINK_SYNTAX_REACT_EXTENSION,
  CODE_SYNTAX_REACT_EXTENSION,
  TABLE_SYNTAX_REACT_EXTENSION,
];

export const SYNTAX_MARKDOWN_SHORTCUTS: ReadonlyArray<Transformer> = [
  ...HEADING_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...QUOTE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...LIST_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...TABLE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...THEMATIC_BREAK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...CODE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...INLINE_MARK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...IMAGE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...LINK_MARKDOWN_SHORTCUT_TRANSFORMERS,
];
