packages:
  - apps/*
  - packages/*

nodeLinker: hoisted
catalogMode: prefer
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - fs-xattr
  - macos-alias
catalog:
  "@lingui/babel-plugin-lingui-macro": 6.0.1
  "@lingui/core": 6.0.1
  "@lingui/react": 6.0.1
  "@lingui/vite-plugin": 6.0.1
  "@rolldown/plugin-babel": ^0.2.2
  "@tailwindcss/vite": ^4.2.2
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  babel-plugin-react-compiler: ^1.0.0
  node-gyp: ^12.4.0
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  msw: true
  protobufjs: true
