import type { Transformer } from "@lexical/markdown";

import { BREAK_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./break";
import { CODE_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./code";
import { HEADING_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./heading";
import { IMAGE_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./image";
import { INLINE_MARK_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./inline-mark";
import { LINK_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./link";
import { LIST_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./list";
import { QUOTE_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./quote";
import { TABLE_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./table";
import { THEMATIC_BREAK_MARKDOWN_SHORTCUT_TRANSFORMERS } from "./thematic-break";

export const MARKDOWN_SHORTCUT_TRANSFORMERS: Transformer[] = [
  ...BREAK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...HEADING_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...QUOTE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...LIST_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...TABLE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...THEMATIC_BREAK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...CODE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...INLINE_MARK_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...IMAGE_MARKDOWN_SHORTCUT_TRANSFORMERS,
  ...LINK_MARKDOWN_SHORTCUT_TRANSFORMERS,
];
