import type { EditorThemeClasses } from "lexical";

export const blockEditorLexicalTheme: EditorThemeClasses = {
  paragraph: "block-editor__paragraph",
  quote: "block-editor__quote",
  heading: {
    h1: "block-editor__heading block-editor__heading--h1",
    h2: "block-editor__heading block-editor__heading--h2",
    h3: "block-editor__heading block-editor__heading--h3",
    h4: "block-editor__heading block-editor__heading--h4",
    h5: "block-editor__heading block-editor__heading--h5",
    h6: "block-editor__heading block-editor__heading--h6",
  },
  list: {
    ol: "block-editor__list block-editor__list--ordered",
    ul: "block-editor__list block-editor__list--unordered",
    checklist: "block-editor__list block-editor__list--checklist",
    listitem: "block-editor__list-item",
    listitemChecked: "block-editor__list-item block-editor__list-item--checked",
    listitemUnchecked: "block-editor__list-item block-editor__list-item--unchecked",
    nested: {
      list: "block-editor__list block-editor__list--nested",
      listitem: "block-editor__list-item--nested",
    },
  },
  text: {
    bold: "block-editor__text--bold",
    italic: "block-editor__text--italic",
    strikethrough: "block-editor__text--strikethrough",
    code: "block-editor__text--code",
  },
  code: "block-editor__code",
  hr: "block-editor__hr",
  hrSelected: "block-editor__hr--selected",
  table: "block-editor__table",
  tableRow: "block-editor__table-row",
  tableCell: "block-editor__table-cell",
  tableCellHeader: "block-editor__table-cell block-editor__table-cell--header",
  tableCellSelected: "block-editor__table-cell--selected",
  tableScrollableWrapper: "block-editor__table-scroll",
  codeHighlight: {
    atrule: "block-editor__token block-editor__token--keyword",
    attr: "block-editor__token block-editor__token--attr",
    boolean: "block-editor__token block-editor__token--constant",
    builtin: "block-editor__token block-editor__token--builtin",
    cdata: "block-editor__token block-editor__token--comment",
    char: "block-editor__token block-editor__token--string",
    class: "block-editor__token block-editor__token--class",
    "class-name": "block-editor__token block-editor__token--class",
    comment: "block-editor__token block-editor__token--comment",
    constant: "block-editor__token block-editor__token--constant",
    deleted: "block-editor__token block-editor__token--deleted",
    doctype: "block-editor__token block-editor__token--comment",
    entity: "block-editor__token block-editor__token--operator",
    function: "block-editor__token block-editor__token--function",
    important: "block-editor__token block-editor__token--keyword",
    inserted: "block-editor__token block-editor__token--inserted",
    keyword: "block-editor__token block-editor__token--keyword",
    namespace: "block-editor__token block-editor__token--variable",
    number: "block-editor__token block-editor__token--number",
    operator: "block-editor__token block-editor__token--operator",
    prolog: "block-editor__token block-editor__token--comment",
    property: "block-editor__token block-editor__token--property",
    punctuation: "block-editor__token block-editor__token--punctuation",
    regex: "block-editor__token block-editor__token--regex",
    selector: "block-editor__token block-editor__token--selector",
    string: "block-editor__token block-editor__token--string",
    symbol: "block-editor__token block-editor__token--constant",
    tag: "block-editor__token block-editor__token--tag",
    url: "block-editor__token block-editor__token--string",
    variable: "block-editor__token block-editor__token--variable",
  },
  link: "block-editor__link",
};
