/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteRouteImport } from './routes/_workspace/route'
import { Route as PreferencesIndexRouteImport } from './routes/preferences/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'

const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/preferences/',
  path: '/preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/lab/': typeof LabIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceIndexRoute
  '/lab': typeof LabIndexRoute
  '/preferences': typeof PreferencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteRouteWithChildren
  '/_workspace/': typeof WorkspaceIndexRoute
  '/lab/': typeof LabIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lab/' | '/preferences/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lab' | '/preferences'
  id: '__root__' | '/_workspace' | '/_workspace/' | '/lab/' | '/preferences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  LabIndexRoute: typeof LabIndexRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/preferences'
      fullPath: '/preferences/'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  LabIndexRoute: LabIndexRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
