import type { EditorThemeClasses } from "lexical";

export const noteEditorLexicalTheme: EditorThemeClasses = {
  paragraph: "note-block-editor__paragraph",
  quote: "note-block-editor__quote",
  heading: {
    h1: "note-block-editor__heading note-block-editor__heading--h1",
    h2: "note-block-editor__heading note-block-editor__heading--h2",
    h3: "note-block-editor__heading note-block-editor__heading--h3",
    h4: "note-block-editor__heading note-block-editor__heading--h4",
    h5: "note-block-editor__heading note-block-editor__heading--h5",
    h6: "note-block-editor__heading note-block-editor__heading--h6",
  },
  list: {
    ol: "note-block-editor__list note-block-editor__list--ordered",
    ul: "note-block-editor__list note-block-editor__list--unordered",
    checklist: "note-block-editor__list note-block-editor__list--checklist",
    listitem: "note-block-editor__list-item",
    listitemChecked: "note-block-editor__list-item note-block-editor__list-item--checked",
    listitemUnchecked: "note-block-editor__list-item note-block-editor__list-item--unchecked",
    nested: {
      list: "note-block-editor__list note-block-editor__list--nested",
      listitem: "note-block-editor__list-item--nested",
    },
  },
  text: {
    bold: "note-block-editor__text--bold",
    italic: "note-block-editor__text--italic",
    strikethrough: "note-block-editor__text--strikethrough",
    code: "note-block-editor__text--code",
  },
  code: "note-block-editor__code",
  hr: "note-block-editor__hr",
  hrSelected: "note-block-editor__hr--selected",
  table: "note-block-editor__table",
  tableRow: "note-block-editor__table-row",
  tableCell: "note-block-editor__table-cell",
  tableCellHeader: "note-block-editor__table-cell note-block-editor__table-cell--header",
  tableCellSelected: "note-block-editor__table-cell--selected",
  tableScrollableWrapper: "note-block-editor__table-scroll",
  codeHighlight: {
    atrule: "note-block-editor__token note-block-editor__token--keyword",
    attr: "note-block-editor__token note-block-editor__token--attr",
    boolean: "note-block-editor__token note-block-editor__token--constant",
    builtin: "note-block-editor__token note-block-editor__token--builtin",
    cdata: "note-block-editor__token note-block-editor__token--comment",
    char: "note-block-editor__token note-block-editor__token--string",
    class: "note-block-editor__token note-block-editor__token--class",
    "class-name": "note-block-editor__token note-block-editor__token--class",
    comment: "note-block-editor__token note-block-editor__token--comment",
    constant: "note-block-editor__token note-block-editor__token--constant",
    deleted: "note-block-editor__token note-block-editor__token--deleted",
    doctype: "note-block-editor__token note-block-editor__token--comment",
    entity: "note-block-editor__token note-block-editor__token--operator",
    function: "note-block-editor__token note-block-editor__token--function",
    important: "note-block-editor__token note-block-editor__token--keyword",
    inserted: "note-block-editor__token note-block-editor__token--inserted",
    keyword: "note-block-editor__token note-block-editor__token--keyword",
    namespace: "note-block-editor__token note-block-editor__token--variable",
    number: "note-block-editor__token note-block-editor__token--number",
    operator: "note-block-editor__token note-block-editor__token--operator",
    prolog: "note-block-editor__token note-block-editor__token--comment",
    property: "note-block-editor__token note-block-editor__token--property",
    punctuation: "note-block-editor__token note-block-editor__token--punctuation",
    regex: "note-block-editor__token note-block-editor__token--regex",
    selector: "note-block-editor__token note-block-editor__token--selector",
    string: "note-block-editor__token note-block-editor__token--string",
    symbol: "note-block-editor__token note-block-editor__token--constant",
    tag: "note-block-editor__token note-block-editor__token--tag",
    url: "note-block-editor__token note-block-editor__token--string",
    variable: "note-block-editor__token note-block-editor__token--variable",
  },
  link: "note-block-editor__link",
};
