/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SampleIndexRouteImport } from './routes/sample/index'
import { Route as NotesIdIndexRouteImport } from './routes/notes/$id/index'

const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleIndexRoute = SampleIndexRouteImport.update({
  id: '/sample/',
  path: '/sample/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdIndexRoute = NotesIdIndexRouteImport.update({
  id: '/notes/$id/',
  path: '/notes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/sample/': typeof SampleIndexRoute
  '/notes/$id/': typeof NotesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/sample': typeof SampleIndexRoute
  '/notes/$id': typeof NotesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/sample/': typeof SampleIndexRoute
  '/notes/$id/': typeof NotesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preferences' | '/sample/' | '/notes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preferences' | '/sample' | '/notes/$id'
  id: '__root__' | '/' | '/preferences' | '/sample/' | '/notes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreferencesRoute: typeof PreferencesRoute
  SampleIndexRoute: typeof SampleIndexRoute
  NotesIdIndexRoute: typeof NotesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample/': {
      id: '/sample/'
      path: '/sample'
      fullPath: '/sample/'
      preLoaderRoute: typeof SampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id/': {
      id: '/notes/$id/'
      path: '/notes/$id'
      fullPath: '/notes/$id/'
      preLoaderRoute: typeof NotesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreferencesRoute: PreferencesRoute,
  SampleIndexRoute: SampleIndexRoute,
  NotesIdIndexRoute: NotesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
