export interface PlaygroundSample {
  id: string;
  label: string;
  markdown: string;
}

export const PLAYGROUND_SAMPLES = [
  {
    id: "syntax-all",
    label: "Syntax all",
    markdown: [
      "# Syntax all",
      "",
      "This preset covers the Markdown syntax currently supported by `@fluxnotes/editor`.",
      "Use it to check import, editing, selection export, and preview output.",
      "",
      "## Heading level 2",
      "",
      "### Heading level 3",
      "",
      "#### Heading level 4",
      "",
      "##### Heading level 5",
      "",
      "###### Heading level 6",
      "",
      "Paragraph with **bold**, *italic*, ~~strike~~, and `inline code`.",
      "Soft break line one  ",
      "soft break line two.",
      "",
      "Visit [Fluxnotes](https://example.com/fluxnotes) or paste a bare URL: https://example.com/docs",
      "",
      "![Remote image](https://placehold.co/640x240/png?text=Remote+image)",
      "",
      '![Asset image](assets://block/photo.png "Asset caption")',
      "",
      "> Quote line one with **formatting**.",
      ">",
      "> Quote line two with a [link](https://example.com).",
      "",
      "- Unordered item",
      "- Nested group",
      "  - Nested item A",
      "  - Nested item B",
      "",
      "1. Ordered first",
      "2. Ordered second",
      "   1. Nested ordered item",
      "",
      "- [ ] Todo item",
      "- [x] Done item",
      "",
      "| Name | Left | Center | Right |",
      "| :--- | :--- | :---: | ---: |",
      "| Alpha | Ready | Yes | 1 |",
      "| Beta | Review | No | 2 |",
      "",
      "```ts",
      'type PreviewKind = "markdown" | "html";',
      "",
      "const render = (kind: PreviewKind) => `${kind} output`;",
      'console.log(render("markdown"));',
      "```",
      "",
      "---",
      "",
      "End of supported syntax coverage.",
    ].join("\n"),
  },
  {
    id: "writing",
    label: "Writing",
    markdown: [
      "# Product note",
      "",
      "Today we tightened the editor preview flow and kept the writing surface quiet.",
      "",
      "## Decisions",
      "",
      "- Keep source preview close to the editor.",
      "- Prefer small controls with clear labels.",
      "- Make selection export easy to verify.",
      "",
      "Next step: review the exported Markdown and HTML tabs.",
    ].join("\n"),
  },
  {
    id: "empty",
    label: "Empty",
    markdown: "",
  },
] as const satisfies readonly PlaygroundSample[];

export function findPlaygroundSample(sampleId: string): PlaygroundSample {
  return PLAYGROUND_SAMPLES.find((sample) => sample.id === sampleId) ?? PLAYGROUND_SAMPLES[0];
}
